<?php

/*
 * This file is part of the Arnapou GW2Tools package.
 *
 * (c) Arnaud Buathier <arnaud@arnapou.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\RaidMember;
use AppBundle\Entity\RaidRoster;
use AppBundle\Entity\Token;
use Doctrine\ORM\Query\Expr\Join;

/**
 * RaidRosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaidRosterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Token $token
     * @return array
     */
    public function getRosters(Token $token)
    {
        $items = $this->_em->createQueryBuilder()
            ->select('m')
            ->from(RaidRoster::class, 'r')
            ->join(RaidMember::class, 'm', Join::INNER_JOIN, 'r.id = m.roster')
            ->where('m.name = :member OR r.name = :member')
            ->setParameter('member', $token->getName())
            ->orderBy('r.name')
            ->getQuery()
            ->getResult();

        $results = [];
        foreach ($items as $item) {
            $results[] = [
                'member' => $item,
                'roster' => $item->getRoster(),
            ];
        }

        return $results;
    }
}
