<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Token;
use Gw2tool\Fn;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * 
     * @param string $token
     * @return Token
     */
    public function findOneByToken($token) {
        return $this->findOneBy(['token' => $token]);
    }

    /**
     * 
     * @param string $code
     * @return Token
     */
    public function findOneByCode($code) {
        return $this->findOneBy(['code' => $code]);
    }

    /**
     * 
     * @param string $token
     * @return Token
     */
    public function newToken($token) {
        $entity = new Token();
        $entity->setCode($this->generateNewCode());
        $entity->setToken($token);
        $entity->setData([
            'rights' => [
                'account',
                'characters',
            ],
        ]);
        $this->_em->persist($entity);
        $this->_em->flush();
        return $entity;
    }

    /**
     * 
     * @return string
     */
    public function generateNewCode() {
        do {
            $code = Fn::randomString();
        } while ($this->findOneByCode($code));
        return $code;
    }

}
