imports:
    - { resource: config.yml }

parameters:
    gw2apiclient.debug.request: 0
    gw2apiclient.cache.duration: 300
    gw2apiclient.cache.rules: 
        '/v1/guild_details': 3600
        '/v2/account': 3600
        '/v2/guild/': 600
        '/v2/tokeninfo': 86400

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ['gw2frontrequests', 'gw2consolerequests']
    handlers:
        main:
            type:            rotating_file
            max_files:       10
            path:            "%kernel.logs_dir%/%kernel.environment%.log"
            level:           error
            channels:        [!gw2frontrequests, !gw2consolerequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        gw2frontrequests:
            type:            rotating_file
            max_files:       10
            path:            "%kernel.logs_dir%/gw2frontrequests.log"
            level:           debug
            channels:        [gw2frontrequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        gw2consolerequests:
            type:            rotating_file
            max_files:       10
            path:            "%kernel.logs_dir%/gw2consolerequests.log"
            level:           debug
            channels:        [gw2consolerequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        console:
            type:            console
            channels:        [!gw2frontrequests, !gw2consolerequests]
