imports:
    - { resource: config.yml }

parameters:
    gw2apiclient.debug.request: 1
    gw2apiclient.cache.duration: 900
    gw2apiclient.cache.rules: 
        '/v1/guild_details': 3600
        '/v2/account': 1800
        '/v2/guild/': 600
        '/v2/tokeninfo': 86400

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ['gw2frontrequests', 'gw2consolerequests']
    handlers:
        main:
            type:            rotating_file
            max_files:       3
            path:            "%kernel.logs_dir%/%kernel.environment%.log"
            level:           debug
            channels:        [!event, !gw2frontrequests, !gw2consolerequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        gw2frontrequests:
            type:            rotating_file
            max_files:       10
            path:            "%kernel.logs_dir%/gw2frontrequests.log"
            level:           debug
            channels:        [gw2frontrequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        gw2consolerequests:
            type:            rotating_file
            max_files:       10
            path:            "%kernel.logs_dir%/gw2consolerequests.log"
            level:           debug
            channels:        [gw2consolerequests]
            filename_format: '{date}.{filename}'
            date_format:     'Ymd'
        console:
            type:            console
            channels:       [!event, !doctrine, !gw2frontrequests, !gw2consolerequests]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
